# FL6 (plan 2026-09-24-fleet-and-forge.md): checks.fleet-vm -- two machines,
# core (the operator) and forge (the deploy target). The forge boots the
# console bootstrap FL5 ships (pkgs/fleet/fleet-join.nix, applied with
# the throwaway test key) and carries the declared machine as a
# specialisation (D8): one `fleet deploy` switches the bootstrap away in the
# same VM, keeping the test driver's instrumentation. The deploy key and the
# forge's bootstrap come from nixpkgs' throwaway test keys (publicly known
# RFC 9500 material, generated by nobody here, outside this tree); the
# forge's real host key exists only at runtime, so core's eval-time
# declaration pins a stand-in key the machine does not hold -- that stand-in
# is what subtest 7 exercises (no trust on first use through the system
# known_hosts).
{
  pkgs,
  fleetModule,
  fleetPackage,
  fleetJoinTemplate,
}:
let
  keys = import (pkgs.path + "/nixos/tests/ssh-keys.nix") pkgs;

  # The eval-time stand-in for the forge's runtime host key: core's
  # /etc/ssh/ssh_known_hosts names a key the forge does not have, so a plain
  # `ssh deploy@forge` through the system file is refused and nothing is
  # trusted on first use. The enrolment writes the real, scanned key into
  # the runtime hosts/fleet.json the tool reads.
  standInKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILI+XsoX/3cLjEKKe/6FuKD91bemmU/of1raCjTOMQOB";

  fleetFixture = {
    deployKeys = [ keys.snakeOilEd25519PublicKey ];
    lan = {
      subnet = "192.168.1.0/24";
      gateway = "192.168.1.1";
      nameservers = [ "192.168.1.1" ];
    };
    machines = {
      core.roles = [ "operator" ];
      forge = {
        roles = [ "forge" ];
        address = "192.168.1.2";
        prefix = 24;
        interface = "eth1";
        hostKey = standInKey;
        efi = true;
        stateVersion = "25.11";
      };
    };
  };

  # The repo state before the enrolment: core declared, no forge, no lan --
  # `fleet enroll` fills both.
  initialJson = builtins.toJSON {
    deployKeys = [ keys.snakeOilEd25519PublicKey ];
    machines.core.roles = [ "operator" ];
  };
  # The bootstrap, verbatim from the module file FL5 ships: fleet-join.nix
  # is a function since PL27, applied here with the throwaway test key and
  # no parent import. There is no derivation anywhere in this path (the
  # old pkgs.replaceVars form imported a derivation built by this same
  # `pkgs`, tripping both the test framework's node-recursion hazard its
  # own comment used to name and the IFD guard); a plain file imported
  # from the outside evaluates clean.
  joinModule = import fleetJoinTemplate {
    deployKeys = [ keys.snakeOilEd25519PublicKey ];
    parentImports = [ ];
  };

  # FL9: the declared forge plus one marker file, as a system the forge's
  # store image lacks (the forge node extends itself with it below, as
  # nixpkgs' specialisations do). Built on the host, it carries no
  # signature, so only `nix copy --no-check-sigs` by a trusted user lands
  # it (the decision of 2026-09-24).
  unsignedModule =
    { lib, ... }:
    {
      imports = [ fleetModule ];
      fleet = fleetFixture;
      fleet-join.enable = false;
      specialisation = lib.mkForce { };
      # The test framework enables switching only for a node that declares
      # a specialisation; this system declares none and is switched to.
      system.switch.enable = true;
      environment.etc."fleet-unsigned".text = "unsigned\n";
    };
in
pkgs.testers.runNixOSTest {
  name = "fleet";

  # The framework bakes every store path the testScript references into the
  # private store image of any `useNixStoreImage` node, so the ${pkgs.hello}
  # the absence row names would arrive in the forge's image and the row
  # could never fail; only core (a 9p-share node) may see it.
  includeTestScriptReferences = false;

  nodes.core =
    {
      nodes,
      pkgs,
      lib,
      ...
    }:
    {
      imports = [ fleetModule ];
      fleet = fleetFixture;
      environment.systemPackages = [
        fleetPackage
        pkgs.jq
      ];
      environment.etc."fleet-vm/fleet-initial.json".text = initialJson;
      # The forge's closure (with its declared specialisation) so readlink
      # and the --toplevel checks resolve on core; hello is the path the
      # forge lacks (D8's proxy row: the deploy's own copy moves nothing,
      # the declared toplevel being already in the forge's store).
      virtualisation.additionalPaths = [
        pkgs.hello
        nodes.forge.system.build.toplevel
        nodes.forge.system.build.fleetUnsigned
      ];
      nix.settings.substituters = lib.mkForce [ ];
      # The operator's core (hosts/core/agent-prereqs.nix) runs the tool on
      # nix-command; the tool's `nix copy` needs it, so the VM's core runs
      # the same two features.
      nix.settings.experimental-features = [
        "nix-command"
        "flakes"
      ];
      virtualisation.memorySize = 2048;
    };

  nodes.forge =
    {
      lib,
      extendModules,
      ...
    }:
    {
      # The bootstrap, verbatim from the module file FL5 ships. PL27: the
      # file is a function applied above, so joinModule is already the
      # module itself (the old form imported a substituted derivation a
      # second time here -- a bare derivation would be merged
      # attrset-by-attrset, its `system` string colliding with
      # system.stateVersion).
      imports = [ joinModule ];
      # One deterministic answer for the enrolment's route and resolv
      # fetches.
      networking.defaultGateway = "192.168.1.1";
      networking.nameservers = [ "192.168.1.1" ];
      # Signatures stay required (the nix default). An unsigned copy is
      # accepted only with `nix copy --no-check-sigs`, and the receiving
      # daemon honours that flag only for a trusted user -- so the copy
      # row (subtest 10) is what `trusted-users = [ "deploy" ]` decides.
      # `nix-command` is what the copy and the trusted-users probe run on,
      # the same features the operator's core carries
      # (hosts/core/agent-prereqs.nix).
      nix.settings.experimental-features = [ "nix-command" ];
      # The test refuses core's logins on purpose three times (subtest 6);
      # openssh 10's per-source penalties would then reset core's next
      # connections. Core is exempt; every other source keeps the default.
      # Core is the fixture's declared gateway (the framework numbers core
      # 192.168.1.1, attr-name order).
      services.openssh.settings.PerSourcePenaltyExemptList = fleetFixture.lan.gateway;
      # FL9: a login that is not deploy, so the trust boundary has a
      # second side -- the same unsigned copy, refused for this user.
      users.users.other = {
        isNormalUser = true;
        openssh.authorizedKeys.keys = [ keys.snakeOilPublicKey ];
      };
      # The default 9p host-store share would make every host store path
      # (hello included) visible inside the guest, so `test -e` could never
      # observe the copy's absence row (nixpkgs' own nix-serve-ssh test
      # hits the same wall: "Currently due to shared store this is a
      # noop"). The forge gets a private store image instead; the writable
      # overlay is what the deploy's copies land in.
      # switch-to-configuration-ng installs the bootloader on every
      # switch.  nixpkgs' own specialisation machinery pins a
      # specialisation's toplevel to grub "nodev" (no-clone.nix) so its
      # install-grub.pl skips the disk; pin the bootstrap VM the same
      # way or the rollback's switch runs grub-install against the raw
      # ext2 test disk and dies refusing blocklists (grub.device would
      # otherwise be virtio-root from qemu-vm.nix).  The VM direct-boots
      # via qemu -kernel and never reads a bootloader anyway.
      boot.loader.grub.device = lib.mkOverride 0 "nodev";

      virtualisation = {
        useNixStoreImage = true;
        writableStore = true;
        memorySize = 2048;
      };
      # FL9: this node extended with unsignedModule -- a real, switchable
      # system outside the forge's store image (only core registers it).
      system.build.fleetUnsigned =
        (extendModules { modules = [ unsignedModule ]; }).config.system.build.toplevel;
      # The declared forge (D8): the module's sshd, firewall, deploy user
      # and sudo set replace the bootstrap's in one switch.
      specialisation.declared.configuration = {
        imports = [ fleetModule ];
        fleet = fleetFixture;
        fleet-join.enable = false;
        environment.etc."fleet-declared".text = "declared\n";
      };
    };

  testScript =
    { nodes, ... }:
    let
      parent = nodes.forge.system.build.toplevel;
      unsigned = nodes.forge.system.build.fleetUnsigned;
    in
    # python
    ''
      OPTS = "-i /root/.ssh/fleet-deploy -o IdentitiesOnly=yes -o UserKnownHostsFile=/root/kh -o GlobalKnownHostsFile=/dev/null -o StrictHostKeyChecking=yes -o BatchMode=yes"
      parent = "${parent}"
      unsigned = "${unsigned}"

      with subtest("both machines up and reachable"):
          start_all()
          forge.wait_for_unit("sshd.service")
          core.wait_for_unit("multi-user.target")
          core.wait_until_succeeds("ping -c1 192.168.1.2")

      with subtest("keys and the declaration repo"):
          core.succeed("install -Dm600 ${keys.snakeOilEd25519PrivateKey} /root/.ssh/fleet-deploy")
          core.succeed("ssh-keygen -q -t ed25519 -N ''' -f /root/.ssh/rogue")
          core.succeed("mkdir -p /root/repo/hosts/core && printf '# core\\n' > /root/repo/hosts/core/hardware-configuration.nix && cd /root/repo && sha256sum hosts/*/hardware-configuration.nix > hosts/hardware-pins.sha256 && cp /etc/fleet-vm/fleet-initial.json hosts/fleet.json")

      with subtest("the forge's real host key and fingerprint"):
          fp = forge.succeed("ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub | awk '{print $2}'").strip()
          real_key = forge.succeed("cut -d' ' -f1,2 /etc/ssh/ssh_host_ed25519_key.pub").strip()

      with subtest("enrol refused on a fingerprint that is a prefix of the real one"):
          rc, out = core.execute(f"cd /root/repo && fleet enroll forge 192.168.1.2 --fingerprint {fp[:14]} --identity /root/.ssh/fleet-deploy --state-version 25.11 2>&1")
          assert rc == 3, f"expected exit 3, got {rc}: {out}"
          assert "does not match" in out, out
          core.succeed("test ! -e /root/repo/hosts/forge")
          core.succeed("cmp /root/repo/hosts/fleet.json /etc/fleet-vm/fleet-initial.json")

      with subtest("enrol the forge with the real fingerprint"):
          core.succeed(f"cd /root/repo && fleet enroll forge 192.168.1.2 --fingerprint {fp} --identity /root/.ssh/fleet-deploy --state-version 25.11")
          a = core.succeed("sha256sum /root/repo/hosts/forge/hardware-configuration.nix | cut -d' ' -f1")
          b = forge.succeed("nixos-generate-config --show-hardware-config | sha256sum | cut -d' ' -f1")
          assert a == b, f"hardware config differs: {a} vs {b}"
          assert core.succeed("jq -r .machines.forge.hostKey /root/repo/hosts/fleet.json").strip() == real_key
          assert core.succeed("jq -r .machines.forge.interface /root/repo/hosts/fleet.json").strip() == "eth1"
          assert core.succeed("jq -r .machines.forge.prefix /root/repo/hosts/fleet.json").strip() == "24"
          # The forge VM boots BIOS (virtualisation.useEFIBoot stays false).
          assert core.succeed("jq -r .machines.forge.efi /root/repo/hosts/fleet.json").strip() == "false"
          assert core.succeed("jq -r .machines.forge.stateVersion /root/repo/hosts/fleet.json").strip() == "25.11"
          assert core.succeed("jq -r .lan.subnet /root/repo/hosts/fleet.json").strip() == "192.168.1.0/24"
          assert core.succeed("jq -r .lan.gateway /root/repo/hosts/fleet.json").strip() == "192.168.1.1"
          assert core.succeed("jq -r .lan.nameservers[0] /root/repo/hosts/fleet.json").strip() == "192.168.1.1"
          core.succeed("cd /root/repo && sha256sum -c --quiet hosts/hardware-pins.sha256")
          core.succeed("cp /root/repo/hosts/fleet.json /root/fleet.json.good")
          core.succeed("printf 'forge,192.168.1.2 %s\\n' \"$(jq -r .machines.forge.hostKey /root/repo/hosts/fleet.json)\" > /root/kh")

      declared = core.succeed(f"readlink -f {parent}/specialisation/declared").strip()

      with subtest("the undeclared key cannot log in"):
          rc, out = core.execute(f"ssh {OPTS.replace('fleet-deploy', 'rogue')} deploy@192.168.1.2 true 2>&1")
          assert rc != 0 and "Permission denied" in out, out
          rc, out = core.execute(f"cd /root/repo && fleet deploy forge --toplevel {declared} --identity /root/.ssh/rogue 2>&1")
          assert rc == 3 and "Permission denied" in out, out
          # An agent holding the declared key must not rescue the rogue
          # identity: only IdentitiesOnly keeps the agent's key unoffered.
          core.succeed("ssh-agent -a /root/agent.sock >/dev/null && SSH_AUTH_SOCK=/root/agent.sock ssh-add -q /root/.ssh/fleet-deploy")
          rc, out = core.execute(f"cd /root/repo && SSH_AUTH_SOCK=/root/agent.sock fleet deploy forge --toplevel {declared} --identity /root/.ssh/rogue 2>&1")
          assert rc == 3 and "Permission denied" in out, out

      with subtest("the module's own pin refuses trust on first use"):
          rc, out = core.execute("ssh -i /root/.ssh/fleet-deploy -o IdentitiesOnly=yes -o BatchMode=yes deploy@forge true 2>&1")
          assert rc != 0 and "Host key verification failed" in out, out

      with subtest("the tool's pin refuses before anything is copied"):
          core.succeed("cd /root/repo && jq '.machines.forge.hostKey = \"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHm7m00e2naloG1lBVeaovQtDipZNjtMKtakBm1qVNoI\"' hosts/fleet.json > /root/bad.json && cp /root/bad.json hosts/fleet.json")
          rc, out = core.execute(f"cd /root/repo && fleet deploy forge --toplevel {declared} --identity /root/.ssh/fleet-deploy 2>&1")
          assert rc == 3 and "Host key verification failed" in out, out
          assert "fleet: deploy: copy:" not in out, out
          core.succeed("cp /root/fleet.json.good /root/repo/hosts/fleet.json")

      with subtest("the tool trusts only the declaration, not the system file"):
          core.succeed("cp -L /etc/ssh/ssh_known_hosts /root/skh.module && rm /etc/ssh/ssh_known_hosts")
          core.succeed(f"printf 'forge,192.168.1.2 %s\\n' '{real_key}' > /etc/ssh/ssh_known_hosts")
          core.succeed("ssh -i /root/.ssh/fleet-deploy -o IdentitiesOnly=yes -o BatchMode=yes deploy@192.168.1.2 true")
          core.succeed("cp /root/bad.json /root/repo/hosts/fleet.json")
          rc, out = core.execute(f"cd /root/repo && fleet deploy forge --toplevel {declared} --identity /root/.ssh/fleet-deploy 2>&1")
          assert rc == 3 and "Host key verification failed" in out, out
          assert "fleet: deploy: copy:" not in out, out
          core.succeed("cp /root/fleet.json.good /root/repo/hosts/fleet.json")
          core.succeed("rm /etc/ssh/ssh_known_hosts && cp /root/skh.module /etc/ssh/ssh_known_hosts")

      with subtest("the copy of a path the machine lacks (D8's proxy)"):
          forge.fail("test -e ${pkgs.hello}")
          # Signatures stay required: a plain copy of an unsigned path is
          # refused (the gap `fleet deploy`'s own copy has today) ...
          rc, out = core.execute(f"NIX_SSHOPTS='{OPTS}' nix copy --to ssh-ng://deploy@192.168.1.2 ${pkgs.hello} 2>&1")
          assert rc != 0 and "lacks a signature" in out, out
          forge.fail("test -e ${pkgs.hello}")
          # ... and --no-check-sigs lands it only because deploy is trusted.
          core.succeed(f"NIX_SSHOPTS='{OPTS}' nix copy --no-check-sigs --to ssh-ng://deploy@192.168.1.2 ${pkgs.hello}")
          forge.succeed("test -e ${pkgs.hello}")

      with subtest("the bootstrap's shape"):
          core.succeed(f"ssh {OPTS} deploy@192.168.1.2 sudo -n /run/current-system/sw/bin/nixos-generate-config --show-hardware-config | head -1 | grep -q 'Do not modify this file'")
          core.fail(f"ssh {OPTS} deploy@192.168.1.2 sudo -n true")
          core.fail(f"ssh {OPTS} deploy@192.168.1.2 sudo -n {parent}/bin/switch-to-configuration dry-activate")
          core.fail(f"ssh {OPTS} deploy@192.168.1.2 sudo -n /run/current-system/sw/bin/nix-env --profile /nix/var/nix/profiles/system --list-generations")

      with subtest("deploy the declared specialisation"):
          out = core.succeed(f"cd /root/repo && fleet deploy forge --toplevel {declared} --identity /root/.ssh/fleet-deploy")
          assert f"fleet: deployed forge {declared}" in out and f"fleet: previous: {parent}" in out, out
          forge.succeed(f"test \"$(readlink -f /run/current-system)\" = {declared}")
          forge.succeed("test -e /etc/fleet-declared")
          core.succeed(f"ssh {OPTS} deploy@192.168.1.2 true")
          # The bootstrap is gone: its third sudo command is refused, and
          # so is everything but the module's exact two.
          core.fail(f"ssh {OPTS} deploy@192.168.1.2 sudo -n /run/current-system/sw/bin/nixos-generate-config --show-hardware-config")
          core.fail(f"ssh {OPTS} deploy@192.168.1.2 sudo -n true")
          core.fail(f"ssh {OPTS} deploy@192.168.1.2 sudo -n {declared}/bin/switch-to-configuration dry-activate")
          core.fail(f"ssh {OPTS} deploy@192.168.1.2 sudo -n /run/current-system/sw/bin/nix-env --profile /nix/var/nix/profiles/system --list-generations")
          # The pinned openssh (10.5) prints sshd -T's names capitalised
          # ("PasswordAuthentication no", not the old lowercase spelling).
          forge.succeed("sshd -T -f /etc/ssh/sshd_config | grep -qx 'PasswordAuthentication no'")
          forge.succeed("sshd -T -f /etc/ssh/sshd_config | grep -qx 'KbdInteractiveAuthentication no'")
          forge.succeed("sshd -T -f /etc/ssh/sshd_config | grep -qx 'ListenAddress 192.168.1.2:22'")
          forge.succeed("nft list ruleset | grep -qF 'iifname \"eth1\" ip saddr 192.168.1.0/24 tcp dport 22 accept'")
          forge.succeed("nix config show trusted-users | grep -q deploy")

      with subtest("a user other than deploy cannot land an unsigned path"):
          core.succeed("install -Dm600 ${keys.snakeOilPrivateKey} /root/.ssh/other")
          forge.fail(f"test -e {unsigned}")
          rc, out = core.execute(f"NIX_SSHOPTS='{OPTS.replace('fleet-deploy', 'other')}' nix copy --no-check-sigs --to ssh-ng://other@192.168.1.2 {unsigned} 2>&1")
          assert rc != 0 and "lacks a signature" in out, out
          forge.fail(f"test -e {unsigned}")

      with subtest("deploy an unsigned toplevel the forge lacks"):
          out = core.succeed(f"cd /root/repo && fleet deploy forge --toplevel {unsigned} --identity /root/.ssh/fleet-deploy 2>&1")
          assert f"fleet: deployed forge {unsigned}" in out and f"fleet: previous: {declared}" in out, out
          forge.succeed(f"test \"$(readlink -f /run/current-system)\" = {unsigned}")
          forge.succeed("test -e /etc/fleet-unsigned")

      with subtest("roll back to the bootstrap"):
          core.succeed(f"cd /root/repo && fleet deploy forge --toplevel {parent} --identity /root/.ssh/fleet-deploy")
          forge.succeed(f"test \"$(readlink -f /run/current-system)\" = {parent}")
          # The bootstrap's third sudo rule is back -- the same
          # declared/bootstrap pair, switched twice.
          core.succeed(f"ssh {OPTS} deploy@192.168.1.2 sudo -n /run/current-system/sw/bin/nixos-generate-config --show-hardware-config >/dev/null")
    '';
}
