{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.services.helm;
  brokerNames = lib.attrNames (config.services.egress-broker.instances or { });
  # Helm v1 (control surface) — consolidated plan D1/D2/D3. profileNameRegex
  # is the shared shape gate for profile names, workspace names and the
  # /etc/helm/profile marker; agentUnitPrefix is the "profiles never touch
  # agent units" guard (D2). controlWorkspaces is the workspace map in the
  # exact JSON shape serve.py/render.py and helm-open-workspace.sh consume.
  profileNameRegex = "^[a-z][a-z0-9-]{0,31}$";
  agentUnitPrefix = "^(egress-|cowork|basket|restic-backups-|helm-).*";
  controlWorkspaces = lib.mapAttrs (_: w: {
    inherit (w)
      path
      devShell
      basket
      command
      ;
  }) cfg.control.workspaces;
  # The launcher's workspaces reach it as a store file, never spliced into a
  # shell literal: a workspace path/command/devShell/basket may contain a
  # single quote, and builtins.replaceStrings does no shell escaping, so the
  # JSON must stay out of the script body altogether. Only this absolute store
  # path (which Nix mints, so it cannot contain a quote) is substituted.
  workspacesJson = (pkgs.formats.json { }).generate "helm-workspaces.json" controlWorkspaces;
  configJsonAttrs = {
    inherit (cfg) repo;
    operator_user = cfg.operatorUser;
    interval_s = cfg.intervalSeconds;
    restic_repository = cfg.restic.repository;
    restic_password_file = cfg.restic.passwordFile;
    # Outside /var/lib/helm (the served document root) -- restic's internal
    # pack/index cache is not a dashboard file for static-web-server to
    # serve, and a stray /cache/ path on the loopback listener would leak
    # its presence to any local process (audit F17).
    restic_cache_dir = "/var/lib/helm-cache";
    # A systemd --user unit's PATH lacks /run/current-system/sw/bin, where
    # nixos-version (generated by the system) and nvidia-smi (the driver)
    # actually live -- give the collector the absolute path directly
    # instead of relying on the wrapper script's own PATH splicing below,
    # so the drift and gpu tiles can report even if that splicing ever
    # regresses. collect.py falls back to the bare name when a config
    # lacks these keys (e.g. a manual `nix run .#helm-collect`).
    nixos_version_bin = "/run/current-system/sw/bin/nixos-version";
    nvidia_smi_bin = "/run/current-system/sw/bin/nvidia-smi";
    basket_bin = "${cfg.basketPackage}/bin/basket";
    broker_audit_paths = map (n: {
      instance = n;
      path = "/var/lib/egress-broker/${n}/audit.jsonl";
    }) cfg.brokerInstances;
    timers_system = cfg.timers.system;
    timers_user = cfg.timers.user;
    flake_check_file = "/var/lib/helm/flake-check.json";
    out_dir = "/var/lib/helm";
    evidence_dir = cfg.evidenceDir;
  }
  // lib.optionalAttrs cfg.control.enable {
    # The control section serve.py reads at startup (D10/D3): profiles and
    # host_aliases drive the allowlists, listen is the bound address, marker
    # is re-read per request, and kgx_bin/helm_open_workspace_bin are
    # absolute paths because a --user unit's PATH lacks
    # /run/current-system/sw/bin (same reasoning as nixos_version_bin above).
    control = {
      profiles = cfg.control.profiles;
      workspaces = controlWorkspaces;
      host_aliases = cfg.control.hostAliases;
      inherit (cfg) listen;
      marker = "/etc/helm/profile";
      kgx_bin = "/run/current-system/sw/bin/kgx";
      helm_open_workspace_bin = "/run/current-system/sw/bin/helm-open-workspace";
    };
  };
  configJson = (pkgs.formats.json { }).generate "helm-config.json" configJsonAttrs;
  helmCollect = pkgs.writeShellApplication {
    name = "helm-collect";
    runtimeInputs = with pkgs; [
      python3
      restic
      git
      systemd
      coreutils
    ];
    # The drift and gpu tiles now get nixos-version/nvidia-smi as absolute
    # paths from /etc/helm/config.json (nixos_version_bin/nvidia_smi_bin,
    # above) so they don't depend on PATH at all in the normal case. This
    # PATH splice is a second layer, not the fix: /run/current-system/sw/bin
    # isn't a nix package attribute reachable without a cycle (referencing
    # config.system.path here would pull in environment.systemPackages,
    # which includes this very derivation via environment.systemPackages =
    # [ helmStatus helmCollect ] below), and a systemd --user unit doesn't
    # inherit that PATH the way an interactive login shell does -- so if
    # collect.py's config.json ever lacked these keys (its fallback is the
    # bare command name), this still lets it find them.
    # /run/current-system/sw/bin is a stable runtime path on any booted
    # NixOS system, so appending it here at runtime (not eval time) is safe.
    text = ''
      export PATH="$PATH:/run/current-system/sw/bin"
      exec python3 ${../pkgs/helm/collect.py} "$@"
    '';
  };
  helmStatus = pkgs.writeShellApplication {
    name = "helm-status";
    runtimeInputs = [ helmCollect ];
    text = ''exec helm-collect --print "$@"'';
  };
  # E5: the evidence recorder the nightly flake check calls. Embeds the whole
  # pkgs/evidence directory (evidence.py imports its sibling claims.py) and
  # deliberately sets no EVIDENCE_STORE default: the unit sets it and the
  # script passes --store explicitly.
  evidenceCli = pkgs.writeShellApplication {
    name = "evidence";
    runtimeInputs = [
      pkgs.python3
      pkgs.git
    ];
    text = ''exec python3 ${../pkgs/evidence}/evidence.py "$@"'';
  };
  flakeCheck = pkgs.writeShellApplication {
    name = "helm-flake-check";
    runtimeInputs = [
      config.nix.package
      pkgs.git
      pkgs.jq
      pkgs.coreutils
      evidenceCli
    ];
    text = ''
      out=/var/lib/helm/flake-check.json
      cd "$HELM_REPO"
      rev=$(git rev-parse HEAD 2>/dev/null || echo unknown)
      started=$(date -u +%FT%TZ); t0=$(date +%s)
      set +e
      log=$(nix flake check --offline --no-update-lock-file -L 2>&1); code=$?
      set -e
      dur=$(( $(date +%s) - t0 ))
      tail_txt=$(printf '%s\n' "$log" | tail -n 40)
      ok=false; [ "$code" -eq 0 ] && ok=true
      jq -n --arg rev "$rev" --argjson ok "$ok" --argjson exit "$code" --arg started "$started" --argjson dur "$dur" --arg tail "$tail_txt" \
        '{rev:$rev, ok:$ok, exit:$exit, started:$started, duration_s:$dur, log_tail:$tail}' >"$out.tmp"
      chmod 0640 "$out.tmp"; mv "$out.tmp" "$out"
      # E5: the observation the tiles and the bundle reuse (pkgs/evidence/SCHEMA.md).
      if [[ "$rev" =~ ^[0-9a-f]{40}$ ]]; then
        okflag=--fail; [ "$code" -eq 0 ] && okflag=--ok
        printf '%s\n' "$tail_txt" >"$out.tail"
        evidence --store "''${EVIDENCE_STORE:-${cfg.evidenceDir}}" record-check --name flake-check --rev "$rev" "$okflag" --class nix-check --src helm-nightly --duration "$dur" --log-tail-file "$out.tail" \
          || echo "helm-flake-check: observation not recorded (store missing until the switch?)" >&2
        rm -f "$out.tail"
      fi
    '';
  };
  hardened = {
    NoNewPrivileges = true;
    ProtectSystem = "strict";
    ProtectHome = "read-only";
    ReadWritePaths = [ "/var/lib/helm" ];
    PrivateTmp = true;
    CapabilityBoundingSet = "";
    Nice = 10;
    # Files written by these units (status.json, index.html,
    # flake-check.json) must stay group-readable (0640, group "helm") so
    # the DynamicUser static-web-server can read them -- a permissive
    # inherited umask would otherwise widen or narrow that. write_atomic
    # also fchmods explicitly (belt and suspenders: it runs outside a
    # unit too, e.g. under `nix run`, where no UMask= applies).
    UMask = "0027";
  };
  # Helm v1 (control surface, plan Task 3 / consolidated D1–D3). switchScript
  # and openWorkspace are generated from the checked-in templates; the
  # module substitutes the placeholders the same way the bats suites do.
  # switchScript bakes the FIXED literal allowlist (D1) and the marker path,
  # so every toplevel — base and each specialisation — produces a
  # byte-identical script.
  switchScript = pkgs.writeShellApplication {
    name = "helm-switch";
    runtimeInputs = [ pkgs.coreutils ];
    text =
      builtins.replaceStrings
        [ "@PROFILES@" "@MARKER@" ]
        [
          (lib.concatStringsSep " " cfg.control.profiles)
          "/etc/helm/profile"
        ]
        (lib.removePrefix "#!/usr/bin/env bash\n" (builtins.readFile ../pkgs/helm/helm-switch.sh));
  };
  openWorkspace = pkgs.writeShellApplication {
    name = "helm-open-workspace";
    runtimeInputs = with pkgs; [
      jq
      util-linux
    ];
    text =
      builtins.replaceStrings
        [
          "@WORKSPACES_JSON_FILE@"
          # bash/nix absolute paths, for the same reason kgx_bin and
          # helm_open_workspace_bin are absolute in config: the terminal
          # systemd-run --user spawns lacks /run/current-system/sw/bin on
          # PATH (field bug 2026-09-04). These are the system-profile
          # symlinks the host already puts on PATH for the operator.
          "@BASH_BIN@"
          "@NIX_BIN@"
        ]
        [
          "${workspacesJson}"
          "/run/current-system/sw/bin/bash"
          "/run/current-system/sw/bin/nix"
        ]
        (lib.removePrefix "#!/usr/bin/env bash\n" (builtins.readFile ../pkgs/helm/helm-open-workspace.sh));
  };
  # The control backend. serve.py does `import render`, so the whole
  # pkgs/helm tree (not just serve.py) must land in the store beside it —
  # the directory interpolation copies every tracked file there (same reason
  # flake.nix's helmServe uses `${./pkgs/helm}` rather than the bare file).
  helmServe = pkgs.writeShellApplication {
    name = "helm-serve";
    runtimeInputs = [
      pkgs.python3
      pkgs.systemd
    ];
    text = ''exec python3 ${../pkgs/helm}/serve.py "$@"'';
  };
  # ES5 / duktape only: no arrow functions, no let/const, indexOf not
  # includes. The rule never returns polkit.Result.NO — every non-YES path
  # returns undefined so it cannot shadow another module's rule.
  polkitRule = ''
    polkit.addRule(function (action, subject) {
      if (action.id !== "org.freedesktop.systemd1.manage-units") { return undefined; }
      if (action.lookup("verb") !== "start") { return undefined; }
      if (subject.user !== "${cfg.operatorUser}") { return undefined; }
      var unit = action.lookup("unit");
      var allowed = [${
        lib.concatStringsSep ", " (map (p: ''"helm-switch@${p}.service"'') cfg.control.profiles)
      }];
      if (allowed.indexOf(unit) !== -1) { return polkit.Result.YES; }
      return undefined;
    });
  '';
  # D2 agent-unit guard: presence-aware over systemd.units AND
  # systemd.user.units, for each specialisation. Presence is compared with
  # lib.hasAttr first, then .text only when both sides are present — never
  # `(a.text or null) != (b.text or null)`, which collapses "absent" and
  # "attrset-defined with no text" into null==null and misses the change.
  isAgentUnit = name: builtins.match agentUnitPrefix name != null;
  isProfileScoped = p: name: lib.hasSuffix "-${p}.service" name || lib.hasSuffix "-${p}.timer" name;
  agentUnitGuardAssertions =
    let
      classify =
        p: baseUnits: specUnits:
        lib.concatMap (
          name:
          let
            inBase = lib.hasAttr name baseUnits;
            inSpec = lib.hasAttr name specUnits;
            changed = inBase && inSpec && baseUnits.${name}.text != specUnits.${name}.text;
            removed = inBase && !inSpec;
            newUnit = !inBase && inSpec;
            # The guard is "profiles never touch AGENT units" (D2). changed/
            # removed agent units are forbidden outright; a NEW unit is
            # forbidden only when it lands in the agent namespace without the
            # profile suffix. Guarding every new non-agent unit would forbid
            # the profile's own services -- core's gaming specialisation adds
            # gamemoded.service (found by checks.host-core's red run,
            # 2026-09-04), and acceptance #13 requires that switch to work.
            # A new agent unit still fails: helm-control-assertion-negative-
            # agentunit fixture B (new attrset-defined egress- unit) proves it.
            bad =
              (changed && isAgentUnit name)
              || (removed && isAgentUnit name)
              || (newUnit && isAgentUnit name && !(isProfileScoped p name));
            kind =
              if changed then
                "changes"
              else if removed then
                "removes"
              else
                "adds";
          in
          lib.optional bad {
            assertion = false;
            message = "services.helm.control: specialisation '${p}' ${kind} agent unit '${name}' (agent-unit guard)";
          }
        ) (lib.attrNames (baseUnits // specUnits));
    in
    lib.concatLists (
      lib.mapAttrsToList (
        p: spec:
        (classify p config.systemd.units spec.configuration.systemd.units)
        ++ (classify p config.systemd.user.units spec.configuration.systemd.user.units)
      ) config.specialisation
    );
in
{
  options.services.helm = {
    enable = lib.mkEnableOption "Helm: localhost-only status dashboard (docs/superpowers/specs/2026-09-02-helm-design.md)";

    operatorUser = lib.mkOption {
      type = lib.types.str;
      default = "dalhaka";
      description = ''
        The unprivileged user who owns the restic repository, the restic
        password file and the proton-drive-push user journal; runs the
        helm-collect and helm-flake-check user units and is added to the
        helm group.
      '';
    };

    port = lib.mkOption {
      type = lib.types.port;
      default = 7700;
      description = "TCP port static-web-server listens on (loopback only).";
    };

    listen = lib.mkOption {
      type = lib.types.str;
      default = "127.0.0.1:${toString cfg.port}";
      description = ''
        systemd.socket ListenStream for static-web-server. Must start with
        "127.0.0.1:" or "[::1]:" -- asserted at build time. Helm is
        localhost-only until Phase 10 (LAN + WebAuthn).
      '';
    };

    intervalSeconds = lib.mkOption {
      type = lib.types.ints.positive;
      default = 300;
      description = "How often helm-collect.timer regenerates status.json and index.html.";
    };

    repo = lib.mkOption {
      type = lib.types.str;
      default = "/home/${cfg.operatorUser}/nixos-agent-env";
      description = "Path to this repo checkout, used by the drift tile and the nightly flake check.";
    };

    evidenceDir = lib.mkOption {
      type = lib.types.str;
      default = "/var/lib/evidence";
      description = "Where helm-flake-check records observations and the tiles read them (services.evidence-store.path).";
    };

    configJsonValue = lib.mkOption {
      internal = true;
      type = lib.types.attrs;
      default = { };
      description = "The attrset rendered into /etc/helm/config.json; asserted by helm-eval without reading a derivation.";
    };

    restic = {
      repository = lib.mkOption {
        type = lib.types.str;
        default = "/var/lib/restic/core";
        description = "RESTIC_REPOSITORY passed to `restic snapshots` for the backup-snapshot tile.";
      };
      passwordFile = lib.mkOption {
        type = lib.types.str;
        default = "/home/${cfg.operatorUser}/.config/restic/password";
        description = "RESTIC_PASSWORD_FILE passed to `restic snapshots` for the backup-snapshot tile.";
      };
    };

    flakeCheck = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Run `nix flake check --offline --no-update-lock-file` nightly in
          `repo` and record the result for the flake-check tile. Runs
          offline, so it can never make an outbound network call.
        '';
      };
      onCalendar = lib.mkOption {
        type = lib.types.str;
        default = "*-*-* 03:00:00";
        description = "OnCalendar for helm-flake-check.timer.";
      };
    };

    basketPackage = lib.mkOption {
      type = lib.types.package;
      description = "The basket package; its `doctor` subcommand feeds the basket-doctor tile.";
    };

    brokerInstances = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = brokerNames;
      description = ''
        Names of services.egress-broker.instances whose
        /var/lib/egress-broker/<name>/audit.jsonl feeds the broker tile.
        Defaults to every declared instance.
      '';
    };

    timers = {
      system = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = lib.optional (config.services.proton-backup.enable or false
        ) "restic-backups-core-local.timer";
        description = ''
          System-scope timer units the "timers armed" tile audits. A named
          list on purpose, not every declared timer -- auditing every timer
          would make fstrim/nix-gc/etc. block the tile.
        '';
      };
      user = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [
          "proton-drive-push.timer"
          "helm-collect.timer"
        ]
        ++ lib.optional cfg.flakeCheck.enable "helm-flake-check.timer";
        description = "User-scope (operatorUser) timer units the \"timers armed\" tile audits.";
      };
    };

    control = {
      enable = lib.mkEnableOption "Helm v1 control surface: profile switch + workspace launcher on the loopback page (docs/superpowers/plans/2026-09-03-helm-v1-switch-consolidated.md)";

      profiles = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [ "base" ]; # D1: a FIXED literal — never [ "base" ] ++ attrNames config.specialisation
        description = ''
          The explicit, closed profile allowlist. Every toplevel (base and
          each specialisation) bakes this same literal, so the switch script
          allowlist, the polkit enumeration and the config.json control
          section are byte-identical everywhere (D1: specialisations do not
          nest, so deriving this list would diverge inside a specialisation).
        '';
      };

      workspaces = lib.mkOption {
        type = lib.types.attrsOf (
          lib.types.submodule {
            options = {
              path = lib.mkOption {
                type = lib.types.str;
                description = "Absolute path to the workspace's flake checkout.";
              };
              devShell = lib.mkOption {
                type = lib.types.nullOr lib.types.str;
                default = "default";
                description = "devShell attribute to enter; null opens the workspace directory directly (no `nix develop`).";
              };
              basket = lib.mkOption {
                type = lib.types.nullOr lib.types.str;
                default = null;
                description = "Basket id gating this workspace; null for no basket gate.";
              };
              command = lib.mkOption {
                type = lib.types.nullOr lib.types.str;
                default = null;
                description = ''
                  Command to run in the workspace's terminal instead of a
                  plain interactive shell (e.g. "claude" or
                  "dsh-openrouter"). null leaves the operator at an
                  interactive shell.
                '';
              };
            };
          }
        );
        default = { };
        description = "Workspaces the page can open (a terminal in the flake, entering its dev shell when one is declared, at an interactive shell unless a workspace sets `command`).";
      };

      hostAliases = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [
          "localhost"
          "127.0.0.1"
        ];
        description = "Accepted Host-header aliases (with :port) for the loopback server.";
      };
    };
  };

  config = lib.mkMerge [
    (lib.mkIf cfg.enable {
      assertions = [
        {
          assertion = lib.hasPrefix "127.0.0.1:" cfg.listen || lib.hasPrefix "[::1]:" cfg.listen;
          message = "services.helm.listen must be loopback (127.0.0.1:<port> or [::1]:<port>), got '${cfg.listen}' -- Helm is localhost-only until Phase 10";
        }
      ];

      users.groups.helm = { };
      users.users.${cfg.operatorUser}.extraGroups = [ "helm" ];
      services.helm.configJsonValue = configJsonAttrs;

      # 0644, world-readable, no group gate: the file holds paths only (the
      # restic password is referenced by path, never inlined -- see
      # restic_password_file above), and its bytes are already
      # world-readable in the store regardless of the mode set here. Gating
      # it on group "helm" instead broke helm-collect/helm-status in the
      # operator's already-running session and in user@<uid>.service: a
      # NixOS switch never re-credentials a running session's supplementary
      # groups (X-RestartIfChanged=false on the user manager), so the first
      # read after adding the operator to "helm" 403'd until relogin (audit
      # F1).
      environment.etc."helm/config.json" = {
        source = configJson;
        mode = "0644";
      };

      environment.systemPackages = [
        helmStatus
        helmCollect
      ];

      services.static-web-server = {
        enable = true;
        inherit (cfg) listen;
        root = "/var/lib/helm";
      };

      systemd = {
        # 2750, not 0750: the setgid bit is what makes files that
        # helm-collect/helm-flake-check write (0640, owned by operatorUser's
        # primary group -- neither writes a chgrp) inherit group "helm"
        # instead of the writer's primary group. Without it the DynamicUser
        # static-web-server, which only has SupplementaryGroups=helm, can't
        # read status.json/index.html/flake-check.json and the dashboard
        # 403s. Regression-guarded by the helm-eval check in flake.nix.
        tmpfiles.rules = [
          "d /var/lib/helm 2750 ${cfg.operatorUser} helm -"
          # restic's own cache dir, writable despite ProtectHome=read-only on
          # helm-collect.service (Major fix, plan Task 0) -- 0700, so only
          # operatorUser can read it, and outside /var/lib/helm: it holds
          # restic's internal pack/index cache, not a dashboard file
          # static-web-server needs to serve, and it must never be reachable
          # under the document root (audit F17). Group is "helm" (always
          # declared by this module, line above) rather than operatorUser's
          # own name: a normal NixOS user's primary group defaults to
          # "users", not a same-named group, and 0700 makes the group bits
          # moot for access anyway -- naming a nonexistent group here would
          # make systemd-tmpfiles-setup.service fail at boot, which is worse
          # than what it replaces.
          "d /var/lib/helm-cache 0700 ${cfg.operatorUser} helm -"
        ];
        # Only meaningful while static-web-server is actually the server
        # (v0 mode). Under control.enable static-web-server.enable is
        # mkForce'd false (line below), which removes the upstream unit's
        # ExecStart= but NOT this direct serviceConfig definition — a stray
        # serviceConfig then renders a static-web-server.service with no
        # ExecStart= and systemd refuses it ("bad unit file setting", field
        # bug 2026-09-04). Gate it so the whole unit disappears with the
        # upstream module instead of half of it.
        services.static-web-server = lib.mkIf (!cfg.control.enable) {
          serviceConfig = {
            SupplementaryGroups = [ "helm" ];
            # Upstream's own module sets this to the bare (undashed) root,
            # which fails the unit if /var/lib/helm doesn't exist yet -- on a
            # fresh switch this tmpfiles rule and static-web-server.socket can
            # race. The "-" prefix is systemd's own syntax for "skip a missing
            # source instead of failing"; the unit is socket-activated, so the
            # next connection attempt retries the start once tmpfiles has run
            # (no Restart= needed). mkForce because unitOption's merge
            # concatenates list-valued definitions -- without it this would
            # sit alongside upstream's undashed entry rather than replace it
            # (audit F26).
            BindReadOnlyPaths = lib.mkForce [ "-/var/lib/helm" ];
          };
        };
        user = {
          services.helm-collect = {
            description = "Helm: collect status tiles and render the page";
            unitConfig.ConditionUser = cfg.operatorUser;
            # ProtectHome=read-only (in `hardened`) leaves restic with no
            # writable cache otherwise (Major fix, plan Task 0); the
            # collector also sets this explicitly from restic_cache_dir in
            # /etc/helm/config.json, so restic sees it however it's invoked.
            environment.RESTIC_CACHE_DIR = "/var/lib/helm-cache";
            environment.EVIDENCE_STORE = cfg.evidenceDir;
            serviceConfig = hardened // {
              Type = "oneshot";
              TimeoutStartSec = "5min";
              ExecStart = "${helmCollect}/bin/helm-collect --config /etc/helm/config.json --out /var/lib/helm";
              # /var/lib/helm-cache is outside /var/lib/helm (audit F17), so
              # ProtectSystem=strict needs it named explicitly -- only this
              # unit touches restic's cache; helm-flake-check below does not
              # get it. Dashed ("-", systemd's "skip a missing source instead
              # of failing" prefix) for the same reason as static-web-server's
              # BindReadOnlyPaths above and helm-flake-check's own
              # ReadWritePaths below: tmpfiles.rules creates this dir during
              # activation, ahead of this unit's own start, so the dash is
              # belt-and-braces against that ordering, not an expectation
              # that the dir is normally absent.
              ReadWritePaths = hardened.ReadWritePaths ++ [
                "-/var/lib/helm-cache"
                "-${cfg.evidenceDir}"
              ];
            };
          };
          timers.helm-collect = {
            description = "Helm: collect every ${toString cfg.intervalSeconds}s";
            unitConfig.ConditionUser = cfg.operatorUser;
            wantedBy = [ "timers.target" ];
            timerConfig = {
              OnBootSec = "2min";
              OnUnitActiveSec = "${toString cfg.intervalSeconds}s";
            };
          };

          services.helm-flake-check = lib.mkIf cfg.flakeCheck.enable {
            description = "Helm: nightly offline nix flake check of the repo";
            unitConfig.ConditionUser = cfg.operatorUser;
            environment.HELM_REPO = cfg.repo;
            environment.EVIDENCE_STORE = cfg.evidenceDir;
            serviceConfig = hardened // {
              Type = "oneshot";
              TimeoutStartSec = "2h";
              ExecStart = "${flakeCheck}/bin/helm-flake-check";
              # `nix flake check` on a git flake writes the fetcher cache
              # (~/.cache/nix/fetcher-cache-v3.sqlite) and nix's state dir on
              # every run -- every nightly run sees a new repo rev, so the
              # cache is always a miss and the write always happens. The
              # shared `hardened` ReadWritePaths only covers /var/lib/helm,
              # and ProtectHome=read-only otherwise blocks that write, so the
              # check would fail every night with a SQLite "readonly
              # database" error. The leading "-" means a missing dir doesn't
              # fail the unit; %h expands to operatorUser's home in a user
              # unit. Regression-guarded by helm-eval (flake.nix).
              ReadWritePaths = [
                "/var/lib/helm"
                "-%h/.cache/nix"
                "-%h/.local/state/nix"
                "-${cfg.evidenceDir}"
              ];
            };
          };
          timers.helm-flake-check = lib.mkIf cfg.flakeCheck.enable {
            description = "Helm: nightly flake check";
            unitConfig.ConditionUser = cfg.operatorUser;
            wantedBy = [ "timers.target" ];
            timerConfig = {
              OnCalendar = cfg.flakeCheck.onCalendar;
              Persistent = true;
            };
          };
        };
      };
    })
    (lib.mkIf cfg.control.enable {
      assertions = [
        {
          assertion = cfg.enable;
          message = "services.helm.control.enable requires services.helm.enable";
        }
        {
          assertion = lib.elem "base" cfg.control.profiles;
          message = "services.helm.control.profiles must contain \"base\" (the boot-default profile)";
        }
        {
          assertion = lib.all (n: builtins.match profileNameRegex n != null) (
            cfg.control.profiles ++ lib.attrNames cfg.control.workspaces
          );
          message = "services.helm.control: every profile and workspace name must match ^[a-z][a-z0-9-]{0,31}$";
        }
        {
          assertion = lib.all (w: lib.hasPrefix "/" w.path) (lib.attrValues cfg.control.workspaces);
          message = "services.helm.control: every workspace path must be absolute";
        }
        {
          assertion =
            config.environment.etc ? "helm/profile"
            && (builtins.match profileNameRegex (config.environment.etc."helm/profile".text or "") != null);
          message = "services.helm.control: environment.etc.\"helm/profile\" must be set to a valid profile name (^[a-z][a-z0-9-]{0,31}$)";
        }
        {
          # G1 (D1): a profile the page offers must be a specialisation this
          # toplevel can switch to. Checked in the base evaluation only: a
          # specialisation child is evaluated with `specialisation = {}` (they
          # do not nest), and is recognised by its own marker.
          assertion =
            (config.environment.etc."helm/profile".text or "base") != "base"
            || lib.all (p: p == "base" || config.specialisation ? ${p}) cfg.control.profiles;
          message = "services.helm.control.profiles names a profile that is not a declared specialisation: ${
            toString (lib.filter (p: p != "base" && !(config.specialisation ? ${p})) cfg.control.profiles)
          }";
        }
      ]
      ++ agentUnitGuardAssertions;
    })
    (lib.mkIf (cfg.enable && cfg.control.enable) {
      # The control surface replaces static-web-server on :7700 (its
      # DynamicUser/SupplementaryGroups wiring is only meaningful while it
      # is enabled).
      services.static-web-server.enable = lib.mkForce false;
      security.polkit.enable = lib.mkDefault true;
      security.polkit.extraConfig = polkitRule;
      systemd.services."helm-switch@" = {
        description = "Helm: switch to profile %i via switch-to-configuration test";
        serviceConfig = {
          Type = "oneshot";
          TimeoutStartSec = "5min";
          ExecStart = "${switchScript}/bin/helm-switch %i";
          # No environment passthrough: the generated script carries its own
          # PATH (writeShellApplication) and the unit must pass nothing else
          # to a root process.
          #
          # Deliberately NO ProtectHome/PrivateTmp here. The unit's entire
          # job is running the new toplevel's activate script, which writes
          # /home, /root and /run/user (update-users-groups, etc setup, the
          # user-manager reload -- the plan Task 3 hardening ran the
          # activation inside a mount namespace where those were read-only
          # and it failed with "mkdir /home/alice: Read-only file system"
          # and "skipping user alice: /run/user/1000 not found"; proven by
          # checks.helm-control-vm's red run, 2026-09-04 -- the objective
          # test overrides the plan's hardening line). The security
          # boundary of this unit is polkit (verb-scoped, unit-enumerated)
          # plus the script's own baked allowlist and the test-only
          # action, not a mount namespace that breaks the activation.
        };
      };
      systemd.user.services.helm-serve = {
        description = "Helm: loopback control backend (switch + workspace actions)";
        unitConfig.ConditionUser = cfg.operatorUser;
        wantedBy = [ "default.target" ];
        serviceConfig = {
          Restart = "on-failure";
          ExecStart = "${helmServe}/bin/helm-serve --config /etc/helm/config.json --token-file %t/helm/token --lock-file %t/helm/switch.lock --listen ${cfg.listen}";
          # %t/helm holds the per-boot token (0600) and the switch lock;
          # RuntimeDirectory creates it writable under ProtectHome.
          RuntimeDirectory = "helm";
          NoNewPrivileges = true;
          ProtectSystem = "strict";
          ProtectHome = "read-only";
          PrivateTmp = true;
          CapabilityBoundingSet = "";
          # 0077 (not v0's 0027): the only file it writes is the per-boot
          # token, which must be 0600.
          UMask = "0077";
        };
      };
      environment.systemPackages = [ openWorkspace ];
    })
  ];
}
