"""Generate a markdown map of the repository tree (plan 2026-09-05-session-context, G2)."""

from __future__ import annotations

import argparse
import os
import pathlib
import re
import subprocess
import sys

HEADER = "# Repo map — generated by pkgs/evidence/repomap.py, do not edit (regenerate: python3 pkgs/evidence/repomap.py write)"


def first_comment(path) -> str:
    """Return the first comment/docstring line of `path`, else "(no description)"."""
    try:
        lines = path.read_text().splitlines()
    except OSError:
        return "(no description)"
    if not lines:
        return "(no description)"
    if lines[0].lstrip().startswith('"""'):
        inner = lines[0].split('"""', 2)[1]
        if '"""' in inner:
            inner = inner[: inner.index('"""')]
        return inner.strip()
    for line in lines[:12]:
        if line.lstrip().startswith("#!"):
            continue
        m = re.match(r"^\s*(#|//)\s*(.+)$", line)
        if m:
            return m.group(2).strip()
    return "(no description)"


def flake_check_names(flake_text: str) -> list[str]:
    """Return check names declared between ``checks.${system} = {`` and its closing ``};``."""
    names: list[str] = []
    in_checks = False
    for line in flake_text.splitlines():
        if not in_checks:
            if line.rstrip() == "      checks.${system} = {":
                in_checks = True
            continue
        if line.rstrip() == "      };":
            break
        m = re.match(r"^ {8}([a-z][a-z0-9-]*) =", line)
        if m:
            names.append(m.group(1))
    return names


def _rel(root: pathlib.Path, p: pathlib.Path) -> str:
    return p.relative_to(root).as_posix()


def _package_desc(d: pathlib.Path) -> str:
    name = d.name
    for ext in (".sh", ".py"):
        cand = d / f"{name}{ext}"
        if cand.is_file():
            return first_comment(cand)
    default = d / "default.nix"
    if default.is_file():
        return first_comment(default)
    scripts = sorted(
        (p for p in d.iterdir() if p.is_file() and p.suffix in (".py", ".sh")),
        key=lambda p: p.name,
    )
    if scripts:
        return first_comment(scripts[0])
    return "(no description)"


def _readme_heading(d: pathlib.Path) -> str | None:
    readme = d / "README.md"
    if not readme.is_file():
        return None
    for line in readme.read_text().splitlines():
        m = re.match(r"^#\s+(.+?)\s*$", line)
        if m:
            return m.group(1)
    return None


def _tool_dir_desc(d: pathlib.Path) -> str:
    heading = _readme_heading(d)
    if heading is not None:
        return heading
    scripts = sorted(
        (
            p
            for p in d.rglob("*")
            if p.is_file() and (p.suffix in (".sh", ".py", ".js") or p.suffix == "")
        ),
        key=lambda p: p.as_posix(),
    )
    if scripts:
        return first_comment(scripts[0])
    return "(no description)"


_IGNORED_PARTS = {"__pycache__", ".pytest_cache", ".ruff_cache", ".git"}


_INHERITED_REPO_ENV = ("GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE", "GIT_COMMON_DIR")


def _git_tracked_files(d: pathlib.Path):
    """Tracked files under `d`, or None when `git` is unavailable or `d` is
    not inside a repo (the caller falls back to a directory walk).

    A `git commit` pre-commit hook (notably from a linked worktree) runs with
    GIT_DIR/GIT_WORK_TREE/GIT_INDEX_FILE/GIT_COMMON_DIR already set in its own
    environment. Left in place, they leak into this `-C d` call: with GIT_DIR
    set but no matching GIT_WORK_TREE, git treats `d` itself as the worktree
    root instead of discovering it fresh from `d`, so `ls-files` stops
    scoping to `d` and dumps every tracked path in the whole repo instead.
    Scrubbing them forces normal discovery rooted at `d`.
    """
    env = {k: v for k, v in os.environ.items() if k not in _INHERITED_REPO_ENV}
    try:
        r = subprocess.run(
            ["git", "-C", str(d), "ls-files"],
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
            env=env,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if r.returncode != 0:
        return None
    return [ln for ln in r.stdout.splitlines() if ln.strip()]


def _count_files(d: pathlib.Path) -> int:
    tracked = _git_tracked_files(d)
    if tracked is not None:
        return len(tracked)
    n = 0
    for p in d.rglob("*"):
        if not p.is_file():
            continue
        if p.suffix == ".pyc" or any(part in _IGNORED_PARTS for part in p.parts):
            continue
        n += 1
    return n


def build_map(root) -> dict:
    """Build the repo map dict for the tree rooted at `root`."""
    root = pathlib.Path(root)

    modules = [
        {"path": _rel(root, f), "desc": first_comment(f)}
        for f in sorted((root / "nixosModules").glob("*.nix"))
    ]

    packages = [
        {"path": _rel(root, d).rstrip("/"), "desc": _package_desc(d)}
        for d in sorted((root / "pkgs").glob("*"))
        if d.is_dir()
    ]

    flake = root / "flake.nix"
    checks = flake_check_names(flake.read_text()) if flake.is_file() else []

    tests: list[dict] = []
    tests_dir = root / "tests"
    for d in sorted(tests_dir.glob("*")):
        if d.is_dir():
            tests.append({"path": _rel(root, d), "files": _count_files(d)})
    for f in sorted(tests_dir.glob("*.nix")):
        tests.append({"path": _rel(root, f), "files": 1})
    tests.sort(key=lambda e: e["path"])

    hosts = [
        {"path": _rel(root, f), "desc": first_comment(f)}
        for f in sorted((root / "hosts").glob("*/*.nix"))
    ]

    tools: list[dict] = []
    for p in sorted((root / "tools").glob("*")):
        if p.is_file():
            tools.append({"path": _rel(root, p), "desc": first_comment(p)})
        elif p.is_dir():
            tools.append({"path": _rel(root, p), "desc": _tool_dir_desc(p)})
    tools.sort(key=lambda e: e["path"])

    return {
        "modules": modules,
        "packages": packages,
        "checks": checks,
        "tests": tests,
        "hosts": hosts,
        "tools": tools,
    }


def render_map(m) -> str:
    """Render the repo map dict as markdown starting with HEADER."""
    out = [
        HEADER,
        "",
        "Paths are repo-relative. Descriptions are each file's first comment line.",
        "",
    ]

    def kv_section(title: str, items):
        out.append(f"## {title}")
        out.append("")
        for item in items:
            out.append(f"- `{item['path']}` — {item['desc']}")
        out.append("")

    kv_section("NixOS modules", m["modules"])
    kv_section("Packages", m["packages"])

    out.append("## Checks (nix build .#checks.x86_64-linux.<name>)")
    out.append("")
    for name in m["checks"]:
        out.append(f"- {name}")
    out.append("")

    out.append("## Tests")
    out.append("")
    for item in m["tests"]:
        out.append(f"- `{item['path']}` — {item['files']} files")
    out.append("")

    kv_section("Hosts", m["hosts"])
    kv_section("Tools", m["tools"])

    return "\n".join(out)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="repomap")
    parser.add_argument("--root", default=".")
    parser.add_argument("command", choices=["write", "check", "print"])
    args = parser.parse_args(argv)

    root = pathlib.Path(args.root)
    md = render_map(build_map(root))
    map_path = root / "docs" / "MAP.md"

    if args.command == "write":
        map_path.parent.mkdir(parents=True, exist_ok=True)
        map_path.write_text(md)
        return 0
    if args.command == "print":
        print(md, end="")
        return 0

    # check
    try:
        existing = map_path.read_text()
    except OSError:
        existing = None
    if existing != md:
        print(
            "repomap: docs/MAP.md is stale — run: python3 pkgs/evidence/repomap.py write",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
