"""The subsystem manifest validator and generator (plan 2026-09-09-program, PR1).

`docs/ledger/subsystems.toml` declares the eight subsystems (charter §2) plus
`program`. `subsystems.py validate` is the every-path-owned check: every tracked
path must match exactly one row's `owns` globs (0 matches -> "uncovered", 2+
-> "ambiguous"). `subsystems.py write` regenerates `docs/subsystems.md` (a
table: subsystem, prefix, area, gate, depends) and, under `--check`, exits 1
when the on-disk page differs; the page is a function of the manifest alone,
never of the file list, so it does not go stale when unrelated files land.
`subsystems.py validate --counts` prints one `<name>: <n>` owned-path line per
row to stdout and writes nothing.

Glob semantics are `task-classes.toml`'s: `*` spans `/`, no `**`, and a glob
must match `tasks.CLASS_GLOB_RE`. Paths are matched with the stdlib
`fnmatch.fnmatch`; the only import from `tasks` is `CLASS_GLOB_RE` — no matcher
is copied from `tasks.py`.
"""

from __future__ import annotations

import argparse
import fnmatch
import os
import pathlib
import subprocess
import sys

import tomllib

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from tasks import CLASS_GLOB_RE

FIELDS = ("name", "prefix", "area", "gate", "owns", "plans", "depends")
GATES = ("opus", "sonnet")

HEADER = (
    "# Subsystems — generated by pkgs/evidence/subsystems.py, do not edit "
    "(regenerate: python3 pkgs/evidence/subsystems.py write docs/ledger/subsystems.toml --root .)"
)


def _load_rows(text: str) -> list[dict]:
    """All `[[subsystem]]` tables, in file order, without validation."""
    data = tomllib.loads(text)
    subs = data.get("subsystem", [])
    if isinstance(subs, dict) or subs is None:
        return []
    return [r for r in subs if isinstance(r, dict)]


def _find_cycle(by_name: dict) -> list[str] | None:
    """A dependency cycle as a name path, or None when `by_name` is acyclic."""
    state: dict[str, int] = {}
    stack: list[str] = []

    def visit(name: str) -> list[str] | None:
        s = state.get(name, 0)
        if s == 2:
            return None
        if s == 1:
            idx = stack.index(name)
            return stack[idx:] + [name]
        state[name] = 1
        stack.append(name)
        for dep in by_name.get(name, {}).get("depends", []):
            if dep not in by_name:
                continue  # a dangling edge is reported separately
            cyc = visit(dep)
            if cyc is not None:
                return cyc
        stack.pop()
        state[name] = 2
        return None

    for name in by_name:
        cyc = visit(name)
        if cyc is not None:
            return cyc
    return None


def validate(text: str, files: list[str]) -> list[str]:
    """Every refusal as a line; empty means the manifest is sound."""
    try:
        rows = _load_rows(text)
    except tomllib.TOMLDecodeError as exc:
        return [f"subsystems: {exc}"]
    if not rows:
        return ["subsystems: not a [[subsystem]] table"]

    errs: list[str] = []
    for i, entry in enumerate(rows, 1):
        for f in FIELDS:
            if f not in entry:
                errs.append(f"subsystem {i}: missing field '{f}'")

    complete = [r for r in rows if all(f in r for f in FIELDS)]

    for field in ("name", "prefix", "area"):
        first: dict[str, str] = {}
        for r in complete:
            v = r[field]
            if v in first:
                errs.append(f"duplicate {field} '{v}' ({first[v]}, {r['name']})")
            else:
                first[v] = r["name"]

    for r in complete:
        if r["gate"] not in GATES:
            errs.append(f"unknown gate '{r['gate']}' in '{r['name']}'")
        if not r["plans"]:
            errs.append(f"no plans for '{r['name']}'")
        for glb in list(r["owns"]) + list(r["plans"]):
            if CLASS_GLOB_RE.fullmatch(glb) is None:
                errs.append(f"glob '{glb}' in '{r['name']}' is not a plain pattern")

    by_name: dict[str, dict] = {}
    for r in complete:
        by_name.setdefault(r["name"], r)

    for r in complete:
        for dep in r["depends"]:
            if dep not in by_name:
                errs.append(f"dangling dependency '{dep}' in '{r['name']}'")

    cycle = _find_cycle(by_name)
    if cycle is not None:
        errs.append(f"dependency cycle: {' -> '.join(cycle)}")

    owners = [(r["name"], glb) for r in complete for glb in r["owns"]]
    for path_ in sorted(files):
        matches = sorted(
            {name for (name, glb) in owners if fnmatch.fnmatch(path_, glb)}
        )
        if not matches:
            errs.append(f"uncovered: {path_}")
        elif len(matches) > 1:
            errs.append(f"ambiguous: {path_} ({', '.join(matches)})")

    return errs


def counts(text: str, files: list[str]) -> list[tuple[str, int]]:
    """One ``(name, owned-path-count)`` pair per row, in file order."""
    rows = _load_rows(text)
    owners = [(r["name"], glb) for r in rows for glb in r["owns"]]
    tally = {r["name"]: 0 for r in rows}
    for path_ in files:
        for name in {name for (name, glb) in owners if fnmatch.fnmatch(path_, glb)}:
            tally[name] += 1
    return [(r["name"], tally[r["name"]]) for r in rows]


def render(text: str, files: list[str]) -> str:
    """The `docs/subsystems.md` page — a function of the manifest alone.

    `files` is accepted for call-site symmetry with `validate`/`counts` but is
    intentionally unused: the page carries no per-subsystem path count, so it
    must not go stale when the file list changes.
    """
    del files  # the page is a function of the manifest, never the file list
    rows = _load_rows(text)
    lines = [
        HEADER,
        "",
        "| Subsystem | Prefix | Area | Gate | Depends |",
        "| --- | --- | --- | --- | --- |",
    ]
    for r in rows:
        deps = ", ".join(r["depends"])
        lines.append(
            f"| {r['name']} | {r['prefix']} | {r['area']} | {r['gate']} | {deps} |"
        )
    return "\n".join(lines) + "\n"


def _files_list(args) -> list[str]:
    if getattr(args, "root", None):
        out = subprocess.run(
            ["git", "-C", args.root, "ls-files"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout
        return sorted(line for line in out.splitlines() if line)
    if getattr(args, "files", None):
        return sorted(
            line for line in pathlib.Path(args.files).read_text().splitlines() if line
        )
    return []


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="subsystems.py")
    sp = p.add_subparsers(dest="command", required=True)

    for name in ("validate", "write"):
        sub = sp.add_parser(name)
        sub.add_argument("toml")
        grp = sub.add_mutually_exclusive_group(required=True)
        grp.add_argument("--root")
        grp.add_argument("--files")

    v = sp.choices["validate"]
    v.add_argument("--counts", action="store_true")

    w = sp.choices["write"]
    w.add_argument("--check")
    w.add_argument("--out")

    args = p.parse_args(argv)
    text = pathlib.Path(args.toml).read_text()
    files = _files_list(args)

    if args.command == "validate":
        errs = validate(text, files)
        for line in errs:
            print(line, file=sys.stderr)
        if errs:
            return 1
        if args.counts:
            for name, n in counts(text, files):
                print(f"{name}: {n}")
        return 0

    out = render(text, files)
    if args.check:
        target = args.check
        existing = (
            pathlib.Path(target).read_text() if pathlib.Path(target).exists() else None
        )
        if existing == out:
            return 0
        print(
            f"subsystems: {target} is stale (regenerate: "
            f"python3 pkgs/evidence/subsystems.py write {args.toml} --root .)",
            file=sys.stderr,
        )
        return 1
    if args.out:
        target = args.out
    elif args.root:
        target = os.path.join(args.root, "docs", "subsystems.md")
    else:
        print("subsystems: write needs --check, --out or --root", file=sys.stderr)
        return 2
    pathlib.Path(target).write_text(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
